# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Heading
  description: Select a heading level and add text
  icon: 'title'
  tags:

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:generic/heading
  ingredients:
  image: 
  image_alt: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: