# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Heading
  description: Select a heading level and add text
  icon: 'title'
  tags:

# Defines the structure of this component, as well as the default values
blueprint:
  text: Heading text
  heading_heirarchy: h2
  heading_size: 'md'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text: 
    type: textarea
  heading_heirarchy:
    type: select
    options: 
      values: 
        - h1
        - h2 
        - h3 
        - h4
        - h5
        - paragraph
  heading_size: 
    type: select
    options: 
      values: 
        - name: Extra Large (24px)
          id: 2xl
        - name: Extra Large (20px)
          id: xl
        - name: Large (18px)
          id: lg
        - name: Medium (16px)
          id: md
        - name: Small (14px)
          id: sm
        - name: Extra Small (12px)
          id: xs